[package]
name = "fib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name="fib_lec2"
path="src/fib_lec2.rs"

[dependencies]
halo2_proofs = "0.1.0"
